### ISSUE TITLE
Update with Trains?

### ISSUE THREAD

**Issue by Ferryman-Gaming** [ClaudiusMinimus/Create_Potato_Forge#12] opened 2022-10-10 04:58 UTC
Not actually a bug.
Can we get an update to 1.18.2 please. Saw trains in the video but can't actually get them so we can use create v0.5.

**Comment by ClaudiusMinimus** [comment] 2022-10-11 12:06
Duplicate of https://github.com/ClaudiusMinimus/Create_Potato_1.18.x/issues/8

**Closed as completed by ClaudiusMinimus** 2022-10-11 12:06 UTC
Labels: bug
