### ISSUE TITLE
Please Update? Choo Choo

### ISSUE THREAD

**Issue by hamishpo** [ClaudiusMinimus/Create_Potato_Forge#10] opened 2022-10-10 04:56 UTC
**NOT A BUG**
Can we please get an update to 1.18.2 so we can use create v0.5. Needs more trains. <3

**Comment by ClaudiusMinimus** [comment] 2022-10-11 12:06
Duplicate of https://github.com/ClaudiusMinimus/Create_Potato_1.18.x/issues/8

**Closed as completed by ClaudiusMinimus** 2022-10-11 12:06 UTC
Labels: bug
