### ISSUE TITLE
Hey not an issue, just an update please

### ISSUE THREAD

**Issue by MrAero1** [ClaudiusMinimus/Create_Potato_Forge#11] opened 2022-10-10 04:58 UTC
Would love an updated pack with, current mod versions

**Comment by ClaudiusMinimus** [comment] 2022-10-11 12:07
Duplicate of https://github.com/ClaudiusMinimus/Create_Potato_1.18.x/issues/8

**Closed as completed by ClaudiusMinimus** 2022-10-11 12:07 UTC
