### ISSUE TITLE
All aboard the Update Express?

### ISSUE THREAD

**Issue by JustJaydos** [ClaudiusMinimus/Create_Potato_Forge#14] opened 2022-10-10 05:07 UTC
Can we please get an update to 1.18.2? Would be Much appreciated :)

**Comment by ClaudiusMinimus** [comment] 2022-10-11 12:06
Duplicate of https://github.com/ClaudiusMinimus/Create_Potato_1.18.x/issues/8

**Closed as completed by ClaudiusMinimus** 2022-10-11 12:06 UTC
